FROM dreipro/laravel-docker

MAINTAINER Martin + Alex

RUN mkdir -p /opt/phpunit \
 && curl -L -sS https://phar.phpunit.de/phpunit.phar -o /opt/phpunit/phpunit.phar

COPY ./container_content/run_tests.sh /

