version: '2'

services:
  laravel:
    build: .
    image: dreipro/laravel-docker:php-7.0
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      USER: "${USER}"
      OSX: ${_system_name} 
      HOST_OS_TYPE: ${OSTYPE} 

