version: '2'

services:
  laravel-web:
    build: .
    image: herrphon/laravel
    container_name: laravel
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      USER: "${USER}"
      OSX: ${_system_name} 
    

